//
//  CreateOrderRouter.swift
//  CleanStore
//
//  Created by Giuliano Accorsi on 31/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateOrderRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

class CreateOrderRouter: CreateOrderRoutingLogic {
  weak var viewController: CreateOrderViewController?

}
