//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Giuliano Accorsi on 31/05/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder {
    
    enum FormatExpirationDate {
        struct Request {
            var date: Date
        }
        struct Response {
            var date: Date
        }
        
        struct ViewModel {
            var date: String
        }
    }
    
    enum UserInputTextField {
        struct Request {
            var date: Date
        }
        struct Response {
            var date: Date
        }
        
        struct ViewModel {
            var date: String
        }
    }
}

struct FormSection {
    struct Field {
        enum FieldType {
            case textFieldSection
            case switchSection
        }
        
        enum TextFieldKeyboardType {
            case email
            case numberPad
            case normal
            case decimalPad
        }
        let text: String
        let keyboardType: TextFieldKeyboardType
        let type: FieldType
    }
    let name: String
    let fields: [Field]
    
}
